# Generated by Django 5.0.6 on 2024-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('roomno', models.CharField(max_length=5)),
                ('seats', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentid', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('classid', models.CharField(max_length=24)),
                ('techerid', models.CharField(max_length=25)),
                ('book', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('tsalary', models.CharField(max_length=25)),
                ('tclass', models.CharField(max_length=5)),
                ('pic', models.FileField(upload_to='')),
                ('created', models.CharField(max_length=25)),
                ('address', models.TextField()),
            ],
        ),
    ]
