# Generated by Django 5.0.6 on 2024-07-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_class_loginuser_studentattendence_subject_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='phone',
            new_name='number',
        ),
    ]
