# Generated by Django 5.0.6 on 2024-07-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_class_seats_alter_student_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.FileField(upload_to='media/'),
        ),
    ]
