# Generated by Django 5.0.6 on 2024-07-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_student_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='techerid',
            new_name='teacherid',
        ),
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
