# Generated by Django 5.0.6 on 2024-07-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_techerid_subject_teacherid_alter_student_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendence',
            name='status',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.FileField(upload_to=' '),
        ),
    ]
