# Generated by Django 5.0.6 on 2024-07-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_studentattendence_status_alter_teacher_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendence',
            name='sclass',
            field=models.CharField(default='', max_length=15),
        ),
    ]
