# Generated by Django 5.0.6 on 2024-07-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_studentattendence_sclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendence',
            name='studentname',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
