# Generated by Django 5.0.6 on 2024-07-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.CharField(max_length=25),
        ),
    ]
